version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: blue-nebula-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password_change_this
      MONGO_INITDB_DATABASE: blue_nebula_hosting
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - blue-nebula-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    # Only expose internally (remove ports for production)
    # ports:
    #   - "27017:27017"

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blue-nebula-backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://admin:secure_password_change_this@mongodb:27017/blue_nebula_hosting?authSource=admin
      - DB_NAME=blue_nebula_hosting
      - JWT_SECRET_KEY=your_super_secure_jwt_secret_key_change_this
      - UPTIME_KUMA_API_KEY=uk1_USvIQkci-6cYMA5VcOksKY7B1TzT7ul2zrvFOniq
    ports:
      - "8001:8001"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - blue-nebula-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blue-nebula-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - blue-nebula-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  blue-nebula-network:
    driver: bridge